language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 5m bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: QXx5jEr8TcuEAvCDBB6sNTM39nvCOC1N1lzlVKjav1/4iiKloayt9k2DVbxRyYQy/X7kdLinzwW04ziEkSgf71d63YU1Tfsa+I2wbR+IglvEgOEBYHRwVK3LK80RbJlUnWMP1fuNt9sYithyvzJvqsJJn64qzGyWRNlodPn3rZRd5fZMtmq4Gd5fRRR7+7ZOy/PfDK/Em1xZ5Mq77K1CNUGz2FsiMLswfJSr//rGo1k0PtyQTCILORCSwACdHLbI5jjFt8U4JUnGlSajEI1XKf/SoqT06LfyEjrDXCBRdt7dpdWmQ0SXf/EInzQpi+qQNFBZymTJbVZ6CZqNuIYZDphTjXLKQJbjWEGYJihlCf+XfXpwC6zhNG0ezmj7//cWcVavl2vzR4u3nARJs+6KVcUJwkYKr2HP9a49p3fwxeG81zv6QECCmfU1g+RyDcuvdDz5ByiQjbdToiBaR0EiG8G9ki6erhjMglW4SuyYSrybb2qpm0EWTgZ6/skDW0ZKaYVW/2625mvrvOZjqekGcxmvlJ34wTlKjo6zHmJ7PHBrsGWNd4Ti36UekCp/wvas7uo745gI3IBBbPho3SoQoMkcqUUwAkJ+VVTQthOnbboKwCRbaY2Drv9n7FKOokE3xp7gCdMpkI4mDh2iLzLQaA8V2Wh1ojROKQt1/0q9Rs4=
    on_success: always
